### ISSUE TITLE
Generation Speed

### ISSUE THREAD

**Issue by jaketanderson** [zhiruiliao/Sc2Mol#2]
Hi @zhiruiliao I'm trying out this generative model but I'm finding it incredibly slow to generate random molecules (on the order of a few seconds per random molecule generated). My GPU utilization is only at 2% (NVIDIA 3090). How do I increase the generation speed? One idea I had was increasing the batch size used during evaluation, but line 130 of `vaetransformer.py` seems to imply there can only be one at a time:

https://github.com/zhiruiliao/Sc2Mol/blob/7d7ea659d77c9e97dd9938d3199c2350565adead/vaetransformer.py#L129-L130

How can I speed up random generation? Thanks.

**Comment by zhiruiliao** [comment]
> Hi @zhiruiliao I'm trying out this generative model but I'm finding it incredibly slow to generate random molecules (on the order of a few seconds per random molecule generated). My GPU utilization is only at 2% (NVIDIA 3090). How do I increase the generation speed? One idea I had was increasing the batch size used during evaluation, but line 130 of `vaetransformer.py` seems to imply there can only be one at a time:
> 
> https://github.com/zhiruiliao/Sc2Mol/blob/7d7ea659d77c9e97dd9938d3199c2350565adead/vaetransformer.py#L129-L130
> 
> How can I speed up random generation? Thanks.

Hello, @jaketanderson, thank you for your focus on our  work. 
When the model generates molecules, the current output `predicted_id` depends on the outputs at previous step, as shown in: 
> 
> https://github.com/zhiruiliao/Sc2Mol/blob/7d7ea659d77c9e97dd9938d3199c2350565adead/vaetransformer.py#L149-L165
> 
It is an iteration and will be early stopped if `predicted_id == end`, resulting in that the number of iteration epochs will be not greater than `target_max_len`.

May you can delete the code:
> 
> https://github.com/zhiruiliao/Sc2Mol/blob/7d7ea659d77c9e97dd9938d3199c2350565adead/vaetransformer.py#L130
> 
and 
> 
> https://github.com/zhiruiliao/Sc2Mol/blob/7d7ea659d77c9e97dd9938d3199c2350565adead/vaetransformer.py#L164-L165
> 
to support batch generation. ( I do not try it but I think it will work...)
This change of code will allow the model to generate more than one molecules at a time, but the early stopping will be also removed (meaning that the number of iteration epochs will be fixed to `target_max_len`.
Note that you shold split the result obained in this way by the end token `[EOS]`, since the early stopping is removed (meaning that the model will output dummy tokens until the maximum epoch, even the end token has been output.

I hope this reply will help you.

**Comment by jaketanderson** [comment]
Unfortunately this change by itself does not give me a speedup. Is there something else I need to change? Is it possible to parallelize things so that `model.sample_from_gaussian(zi)` is run for different values of `zi` at the same time?

**Comment by zhiruiliao** [comment]
> Unfortunately this change by itself does not give me a speedup. Is there something else I need to change? Is it possible to parallelize things so that `model.sample_from_gaussian(zi)` is run for different values of `zi` at the same time?

@jaketanderson 
Good news! I have updated the code and it can support batch generation now!
And you do not need to split the results to remove the dummy  tokens like `[EOS]` since I also updated the `token_utils.py`.
I have tested it on my laptop (RTX2060) with a batch size setting of 64, and it cost about 6.7 seconds to generate 64 strings at a time. I believe that it will achieve higher speed on you PC and you can also accelerate it by setting a larger batch if the memory of GPU is available.
Hope this will help you.

**Comment by jaketanderson** [comment]
Great, it works for me! The generation was sped up by a factor of $10^4$. Thank you for all your help!!
